language: python

python:
  - "3.6"

addons:
  postgresql: "10.5"

services:
  - postgresql       

install:
  - pip install pipenv
  - pip install coveralls
  - pipenv install

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - coverage run --source='.' manage.py test --settings=authors.settings
  - coverage report -m

after_success:
  - coveralls