# Generated by Django 2.1.1 on 2018-10-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='article_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='Article Link'),
        ),
    ]
