# Generated by Django 2.1.2 on 2018-10-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='article_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Article Link'),
        ),
    ]
