# Generated by Django 2.1.2 on 2018-10-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20181014_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotifications',
            name='author',
        ),
    ]
