# Generated by Django 2.1.2 on 2018-10-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotifications_article_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='article_link',
            field=models.URLField(db_index=True, max_length=128, unique=True, verbose_name='Article Link'),
        ),
    ]
