# Generated by Django 2.1.2 on 2018-10-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('notifications', '0003_remove_usernotifications_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='author',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.ArticlesModel'),
            preserve_default=False,
        ),
    ]
