<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-10-11 08:28
=======
# Generated by Django 2.1.1 on 2018-10-03 03:04
>>>>>>> [Feature #160577480] Initial Commit

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
=======
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
>>>>>>> [Feature #160577480] Initial Commit
        ),
    ]
