# Generated by Django 2.1.1 on 2018-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
