# Generated by Django 2.1.1 on 2018-10-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181004_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Articles',
            new_name='articles',
        ),
    ]
