# Generated by Django 2.1.2 on 2018-10-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181020_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlighted',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='articles.ArticlesModel'),
        ),
    ]
