# Generated by Django 2.1.1 on 2018-10-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181004_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesmodel',
            options={'ordering': ['-createdAt']},
        ),
    ]
