# Generated by Django 2.1.1 on 2018-10-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181004_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='articlesmodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='articlesmodel',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
