# Generated by Django 2.1.1 on 2018-10-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181004_1835'),
        ('articles', '0005_auto_20181004_1653'),
    ]

    operations = [
    ]
